cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "aws/tap"
tap "leoafarias/fvm"
tap "stripe/stripe-cli"
tap "sanemat/font"
tap "dart-lang/dart"

brew "anyenv"
brew "awsume"
brew "aws-sam-cli"
brew "bat"
brew "bash-completion"
brew "libyaml"
brew "blueutil"
brew "cfn-lint"
brew "cmatrix"
brew "cocoapods"
brew "docker"
brew "ricty"
brew "eslint"
brew "gmp"
brew "go"
brew "node"
brew "gtop"
brew "exa"
brew "git"
brew "git-secrets"
brew "git-flow"
brew "kubernetes-cli"
brew "zlib"
brew "gitmoji"
brew "lolcat"
brew "mysql", restart_service: true
brew "hadolint"
brew "jq"
brew "mas"
brew "pre-commit"
brew "vim"
brew "neofetch"
brew "nodenv"
brew "nodebrew"
brew "pyenv"
brew "pylint"
brew "rsync"
brew "serverless"
brew "redis"
brew "sl"
brew "ruby-build"
brew "rbenv"
brew "shellcheck"
brew "sleepwatcher"
brew "terraform-docs"
brew "readline"
brew "jesseduffield/lazygit/lazygit"
brew "leoafarias/fvm/fvm"
brew "stripe/stripe-cli/stripe"
brew "volta"
brew "libssh2"
brew "libgit2"
brew "openssl@1.1"
brew "tflint"
brew "tfsec"
brew "tree"
brew "yarn"
brew "watch"
brew "wget"
brew "gh"
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-git-prompt"

cask "adobe-creative-cloud"
cask "appcleaner"
cask "aws-vault"
cask "cheatsheet"
cask "docker"
cask "discord"
cask "deepl"
cask "firefox"
cask "fig"
cask "google-chrome"
cask "font-hack-nerd-font"
cask "keyboardcleantool"
cask "ngrok"
cask "kindle"
cask "postman"
cask "rancher"
cask "raycast"
cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
cask "warp"
cask "zoom"


mas "LINE", id: 539883307
mas "Twitter", id: 1482454543
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Microsoft Remote Desktop", id: 1295203466
mas 'Kindle', id: 405399194
mas "Magnet", id: 441258766
